image: gradle:7.4.2-jdk11  # ✅ Stable Gradle + Java image (no Docker setup required)

pipelines:
  default:
    - step:
        name: Build APK
        caches:
          - gradle
        script:
          - echo "✅ Building Android App..."
          - chmod +x ./gradlew
          - ./gradlew clean assembleDebug
        artifacts:
          - app/build/outputs/**/*.apk
