image: cimg/android:2023.11.1

pipelines:
  default:
    - step:
        name: Build APK
        caches:
          - gradle
        script:
          - echo "Starting build"
          - chmod +x ./gradlew
          - ./gradlew clean build
        artifacts:
          - app/build/outputs/**/*.apk
